apiVersion: apps/v1
kind: Deployment

metadata:
  name: edulab-deployment

spec:
  replicas: 3
  selector:
    matchLabels:
      app: edulab-app
  template:
    metadata:
      labels:
        app: edulab-app
    spec:
      containers:
        - name: edulab-container
          image: ramesh040183/edulab:latest
          ports:
           - containerPort: 80
           